import msgsAndAlerts from "../MsgsAndAlerts.js"
export default class ApplicationSetup{
    constructor(){
        this.gameMode=null
        this.colorsGame={   
            top:"black", 
            bottom:"white", 
        }
        this.currentPlayerColor=null
        this.onlineConf={
            timeConnection:null,
            statusPlayers:{
                playerColor:null,
                playerName:null,
                advName:null
            },
            statusCode:null,
        }
        this.historyMovements=[]
        this.gameLogs=[]
        this.endGame=false
        this.limitTime={
            connection:5000
        }
        this.referenceTimes={
            gameTime:0,
            movementTime:0
        }
    }
    updateCurrentPlayerColor(color){
        this.currentPlayerColor=color
    }
    addGame(game){
        this.gameMode=game
        this.endGame=false
    }
    updateEndGame(isEndGame=true){
        this.endGame=isEndGame
    }
    addInformationPlayerOnline(playerName,playerColor,statusCode){
        this.onlineConf.statusPlayers.playerColor=playerColor
        this.onlineConf.statusPlayers.playerName=playerName
        this.onlineConf.statusCode=statusCode
        this.onlineConf.timeConnection=Date.now()
    }
    updateTimeConnection(){
        setTimeout(()=>{
            if(this.endGame===false){
                this.onlineConf.timeConnection=Date.now()
                this.addPlayerLocalStorage()
                this.updateTimeConnection()
            }
        },1000)
    }
    addNamePlayerAdv(advName){
        this.onlineConf.statusPlayers.advName=advName
    }
    addLogGame(information){
        const displayLog = msgsAndAlerts.log.gamelog(information)
        this.gameLogs.push(displayLog)
    }
    clearGame(){
        this.gameMode=null
        this.currentPlayerColor=null
        this.onlineConf.statusPlayers.playerColor=null
        this.onlineConf.statusPlayers.playerName=null
        this.onlineConf.statusPlayers.advName=null
        this.gameLogs=[]
    }
    startGameTimer(startTime){
        this.referenceTimes.gameTime=startTime  
        this.referenceTimes.movementTime=startTime
        this.addTimesLocalStorage()
    }
    updateMovement(movementTime){
        this.referenceTimes.movementTime=movementTime
        this.addTimesLocalStorage()
    }
    updateReferenceTime(referencetimes){
        this.referenceTimes.gameTime=referencetimes.gameTime
        this.referenceTimes.movementTime=referencetimes.movementTime
    }
    addTimesLocalStorage(){
        localStorage.setItem("timesGame", JSON.stringify(this.referenceTimes))
    }
    addPlayerLocalStorage(){
        localStorage.setItem("playerInformation", JSON.stringify(this.onlineConf))
    }
    addHistoryLocalStorage(movement){
        this.historyMovements.push(movement)
        localStorage.setItem("historyPlayer", JSON.stringify(this.historyMovements))
    }
    clearLocalStorage(){
        this.historyMovements=[]
        localStorage.clear()
    }
}

 